name: Automatically Deploy to Vercel on Push (Develop)

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    name: Deploy to vercel
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          curl -X POST ${{ secrets.VERCEL_DEVELOP_DEPLOY }}
