name: Automatically Deploy to Vercel on Push (Master)

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy to vercel
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          curl -X POST ${{ secrets.VERCEL_MASTER_DEPLOY }}
